# Generated by Django 3.1.7 on 2021-02-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='User Name')),
                ('password', models.CharField(max_length=64, verbose_name='User Password')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date/Time')),
            ],
            options={
                'db_table': 'byun_project_users',
            },
        ),
    ]
